### ISSUE TITLE
Version Mismatch - pypi.org vs Github

### ISSUE THREAD

**Issue by bigwave** [geustace/pyenasolar#2]
The version available on pypi.org is 0.2.1 - https://pypi.org/project/pyenasolar/

The version available here is 0.1.6 - https://github.com/geustace/pyenasolar/blob/main/pyenasolar.egg-info/PKG-INFO

The source downloaded from pypi.org is significantly different from the source here.

**Comment by geustace** [comment]
My dev environment got seriously munted. Am trying to sort things out now.

**Comment by geustace** [comment]
Have pushed my local 0.2.1 to this repo. Main difference was being able to run the module standalone for debugging.

python3 __init__.py interrogates my inverter, you will need to change the IP address in the code and outputs the results to pyenasolar.log
